# Site
name: 'Baby Black Box'
description: 'Baby Black Box is an honest blog for first-time and veteran parents.'
logo: 'assets/images/baby-black-box-logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://www.babyblackbox.com'
email: 'koalahealthcare@gmail.com'
email_octopus: '21674cac-e239-11ed-82b6-8fdf931bfeab'
cusdis: '221ea967-e453-4bdd-999f-f2802cba0e26'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Analytics
google_analytics: 'G-GZ087LECC1'
microsoft_clarity: 'gt5f0pv248'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    koalamama:
      name:           Koala Mama
      site:           
      avatar:         assets/images/author.png
      bio:            "From hospitality professional to professional mama, blogger, and wife!"
      email:          lovekoalamama@gmail.com
      twitter:        https://twitter.com/LoveKoalaMama
      instagram:      https://www.instagram.com/LoveKoalaMama/
      pinterest:      https://www.pinterest.com/lovekoalamama/

    flightrecorder:
      name:           Flight Recorder
      site:           
      avatar:         assets/images/fr_profile_sm.jpg
      bio:            "A first-time parent recording his imperfect fathering.  Happy husband, father, rock climber, and healthcare professional."
      email:          fr@babyblackbox.com
      twitter:        
      instagram:      
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Koala Mama
      avatar: /assets/images/author.png


  # only recipes posts
  - scope:
      path: "_recipes"
    values:
      layout: recipe
      author: Koala Mama
      avatar: /assets/images/author.png

  # only parent posts
  - scope:
      path: "parents"
    values:
      layout: post
      author: Koala Mama
      avatar: /assets/images/author.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Timezone
timezone: "America/Los_Angeles"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]