# Site
name: 'Baby Black Box'
description: 'Baby Black Box is an honest blog for first-time and veteran parents.'
logo: 'assets/images/baby-black-box-logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://www.babyblackbox.com'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Flight Recorder
      site:           
      avatar:         assets/images/avatar.jpg
      bio:            "Bio"
      email:          koalahealthcare@gmail.com
      twitter:        https://twitter.com/koalamama

    jane:
      name:           Jane
      site:           
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          koalahealthcare@gmail.com
      twitter:        https://twitter.com/koalamama
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Flight Recorder
      avatar: assets/images/avatar1.jpg


  # only recipes posts
  - scope:
      path: "_recipes"
    values:
      layout: recipe
      author: Flight Recorder
      avatar: /assets/images/avatar1.jpg

  # only parent posts
  - scope:
      path: "parents"
    values:
      layout: post
      author: Flight Recorder
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]